import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { TransitionPage } from "@/components/TransitionPage";
import { StairTransition } from "@/components/StairTransition";
import { NavigationProvider } from "@/contexts/NavigationContext";

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${jetBrainsMono.className}`}>
      <body className="antialiased">
        <NavigationProvider>
          <Header />
          <StairTransition />
          <TransitionPage>{children}</TransitionPage>
        </NavigationProvider>
      </body>
    </html>
  );
}
